mission10/Models/Basket.cs
using System;
using System.Linq;
using System.Collections.Generic;

//Setting up the basket/checkout so that books and quanitites can be saved

namespace mission10.Models
{
    public class Basket
    {
        public List<BasketLineItem> Items { get; set; } = new List<BasketLineItem>();

        public void AddItem(Books book, int qty)
        {
            BasketLineItem line = Items
                .Where(b => b.Books.BookId == book.BookId)
                .FirstOrDefault();

            if (line == null)
            {
                Items.Add(new BasketLineItem
                {
                    Books = book,
                    Quantity = qty
                });
            }
            else
            {
                line.Quantity += qty;
            }
        }

        public double CalculateTotal()
        {
            double sum = Items.Sum(x => x.Quantity * 25);

            return sum;
        }
    }

    public class BasketLineItem
    {
        public int LineID { get; set; }
        public Books Books { get; set; }
        public int Quantity { get; set; }
    }
}

mission10/Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace mission10.Models
{
    public partial class Books
    {
        [Key]
        [Required]
        public long BookId { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Author { get; set; }
        [Required]
        public string Publisher { get; set; }
        [Required]
        public string Isbn { get; set; }
        [Required]
        public string Classification { get; set; }
        [Required]
        public string Category { get; set; }
        public long PageCount { get; set; }
        public double Price { get; set; }
    }
}

mission10/Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace mission10.Models
{
    public partial class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Books> Books { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite("Data Source = Bookstore.sqlite");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Books>(entity =>
            {
                entity.HasKey(e => e.BookId);

                entity.HasIndex(e => e.BookId)
                    .IsUnique();

                entity.Property(e => e.BookId)
                    .HasColumnName("BookID")
                    .ValueGeneratedNever();

                entity.Property(e => e.Author).IsRequired();

                entity.Property(e => e.Category).IsRequired();

                entity.Property(e => e.Classification).IsRequired();

                entity.Property(e => e.Isbn)
                    .IsRequired()
                    .HasColumnName("ISBN");

                entity.Property(e => e.Publisher).IsRequired();

                entity.Property(e => e.Title).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}

mission10/Models/EFBookstoreRepository.cs
using System;
using System.Linq;

namespace mission10.Models
{
	public class EFBookstoreRepository : IBookstoreRepository
	{
        private BookstoreContext context { get; set; }

        public EFBookstoreRepository(BookstoreContext temp)
        {
            context = temp;
        }

        public IQueryable<Books> Books => context.Books;
    }
}

mission10/Models/IBookstoreRepository.cs
using System;
using System.Linq;

namespace mission10.Models
{
	public interface IBookstoreRepository
	{
        IQueryable<Books> Books { get; }
    }
}

mission10/Models/ViewModels/BooksViewModel.cs
using System;
using System.Linq;
using mission10.Models;

namespace mission10.Models.ViewModels
{
	public class BooksViewModel
	{
        public IQueryable<Books> Books { get; set; }
        public PageInfo PageInfo { get; set; }
    }
}

mission10/Models/ViewModels/PageInfo.cs
using System;
namespace mission10.Models.ViewModels
{
	public class PageInfo
	{
        public int TotalNumBooks { get; set; }
        public int BooksPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages => (int)Math.Ceiling((double)TotalNumBooks / BooksPerPage);
    }
}

mission10/Components/TypesViewComponent.cs
using System;
using System.Linq;
using mission10.Models;
using Microsoft.AspNetCore.Mvc;

//Essentially the controller for the view component and filtering the book category

namespace mission10.Components
{
	public class TypesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

mission10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mission10.Models;
using mission10.Models.ViewModels;

namespace mission10.Controllers
{
    public class HomeController : Controller
    {
        private IBookstoreRepository repo;

        public HomeController(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IActionResult Index(string bookType, int pageNum = 1)
        {
            int pageSize = 10;

            var x = new BooksViewModel
            {
                Books = repo.Books
                .Where(b => b.Category == bookType || bookType == null)
                .OrderBy(b => b.Title)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBooks = (bookType == null ? repo.Books.Count() : repo.Books.Where(x => x.Category == bookType).Count()),
                    BooksPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };

            return View(x);
        }

    }
}

mission10/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission10.Infrastructure;
using mission10.Models;

//Setup checkout and access/store books to the basket

namespace mission10.Models.Pages
{
	public class CheckoutModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }

        public CheckoutModel(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
            basket.AddItem(b, 1);

            HttpContext.Session.setJson("basket", basket);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

mission10/Pages/Checkout.cshtml
@page
@model mission10.Models.Pages.CheckoutModel

@*Checkout page layout*@

<h2>My Cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @*Loop through each item in the basket/checkout cart*@ 
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Books.Title</td>
                <td>@i.Quantity</td>
                <td>$@i.Books.Price</td>
                <td>$@(i.Quantity * i.Books.Price)</td>
            </tr>
        }

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>$@Model.basket.CalculateTotal().ToString()</td>
        </tr>
    </tfoot>

</table>

@*Return back to main bookstore page to continue shopping*@
<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

mission10/Pages/_CheckoutLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css//bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        Book Checkout Page
    </div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

mission10/Views/Home/Index.cshtml
@{
}

@model BooksViewModel

<h2>Our Books</h2>

@*Partial view of books and their categories*@
@foreach (Books b in Model.Books)
    {
        <partial name="BookSummary" model="b" />
    }

@*Page buttons*@
<div page-counter="@Model.PageInfo" page-action="Index" page-classes-enabled="true"
     page-class="btn" page-class-normal="btn-outline-dark"
     page-class-selected="btn-primary" class="btn-group pull-right m-1">
</div>

mission10/Views/Shared/BookSummary.cshtml
@{
}

@model Books

@*View component of each book in the bookstore. Each is listed within its own card*@
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>$@Model.Price.ToString()</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">
        <ul>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>Page Count: @Model.PageCount</li>
            <li>Price: @Model.Price</li>
        </ul>
    </div>

    <form method="post" asp-page="/Checkout">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm" style="float:left">Checkout</button>
        </span>
    </form>

</div>

mission10/Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>

<a asp-controller="Home" asp-action="Index" asp-route-bookType="" asp-route-pageNum="1" class="btn btn-outline-secondary">Home</a>

@*Loop through Book categories*@
@foreach (string t in Model)
{
    <a asp-controller="Home" asp-action="Index" asp-route-bookType="@t" asp-route-pageNum="1"
       class="btn @(ViewBag.SelectedType == t ? "btn-primary" : "btn-outline-secondary")">@t.</a>
}

mission10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


@*Layout of the bookstore, with each book being represented as a card and the different book categories filters listed*@
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Mission 10 - Bookstore Project</span>
    </div>

    <div class="row m-1 p-1">
        @*List out book categories*@
        <div class="col-3">
            <vc:types></vc:types>
        </div>

        @*List out books*@
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>